### ISSUE TITLE
Verificar a possibilidade de usar mysql e como integrar isso ao projeto

### ISSUE THREAD

**Issue by ArkanoidSolutions** [ArkanoidSolutions/cadastroassociados#6]
SQLite sucks =P

**Comment by vitorfblima** [comment]
To usando o SQLite3 e tô achando tranquilo. Se baixar o browser, fica muito mais fácil. Acho que ele é a melhor opção pra nosso app desktop.

**Comment by vitorfblima** [comment]
O SQLite atende nossa necessidade.
